<?php
require_once __DIR__.'/../includes/db_connect.php'; require_once __DIR__.'/../includes/auth.php'; requireRole('learner');
$quizId=(int)($_GET['quiz_id']??$_POST['quiz_id']??0); $error=''; $result=null;
$st=$pdo->prepare("SELECT q.*,c.course_name FROM quizzes q JOIN courses c ON c.course_id=q.course_id JOIN enrollments e ON e.course_id=q.course_id AND e.user_id=? WHERE q.quiz_id=?");$st->execute([$_SESSION['user_id'],$quizId]);$quiz=$st->fetch(); if(!$quiz) die('Quiz not found or you are not enrolled.');
$st=$pdo->prepare('SELECT * FROM questions WHERE quiz_id=? ORDER BY question_id');$st->execute([$quizId]);$questions=$st->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$questions){$error='This quiz has no questions yet.';} else { $pdo->beginTransaction(); try { $st=$pdo->prepare('SELECT COALESCE(MAX(attempt_number),0)+1 FROM quiz_attempts WHERE quiz_id=? AND user_id=?');$st->execute([$quizId,$_SESSION['user_id']]);$attemptNo=(int)$st->fetchColumn();$st=$pdo->prepare('INSERT INTO quiz_attempts (quiz_id,user_id,score,attempt_number) VALUES (?,?,0,?)');$st->execute([$quizId,$_SESSION['user_id'],$attemptNo]);$attemptId=(int)$pdo->lastInsertId();$correct=0;foreach($questions as $q){$answer=$_POST['answer'][$q['question_id']]??null;$ok=$answer && $answer===$q['correct_answer'];if($ok)$correct++;$st=$pdo->prepare('INSERT INTO quiz_answers (attempt_id,question_id,selected_answer,is_correct) VALUES (?,?,?,?)');$st->execute([$attemptId,$q['question_id'],$answer,$ok?1:0]);}$score=round(($correct/count($questions))*100,2);$st=$pdo->prepare('UPDATE quiz_attempts SET score=? WHERE attempt_id=?');$st->execute([$score,$attemptId]);$pdo->commit();$result=['score'=>$score,'correct'=>$correct,'total'=>count($questions)];}catch(Throwable $e){$pdo->rollBack();$error='The quiz could not be submitted.';}}
}
$pageTitle='Take Quiz';require __DIR__.'/../includes/header.php';
?><div class="page-heading"><div><div class="eyebrow">LEARNER PORTAL</div><h1><?=e($quiz['title'])?></h1><p><?=e($quiz['course_name'])?></p></div></div><?php if($result):?><section class="dashboard-card"><h2>Quiz Result</h2><div class="result-score"><?=e($result['score'])?>%</div><p>You answered <?=e($result['correct'])?> out of <?=e($result['total'])?> correctly.</p><a class="btn btn-primary" href="dashboard.php">Back to Dashboard</a></section><?php elseif($error):?><div class="alert alert-error"><?=e($error)?></div><?php endif;?><?php if(!$result):?><form method="POST"><input type="hidden" name="quiz_id" value="<?=$quizId?>"><?php foreach($questions as $i=>$q):?><section class="dashboard-card quiz-question"><h3><?=($i+1)?>. <?=e($q['question_text'])?></h3><?php foreach(['A','B','C','D'] as $letter):$field='option_'.strtolower($letter);?><label class="quiz-option"><input type="radio" name="answer[<?=$q['question_id']?>]" value="<?=$letter?>" required><span><strong><?=$letter?>.</strong> <?=e($q[$field])?></span></label><?php endforeach;?></section><?php endforeach;?><button class="btn btn-primary" type="submit">Submit Quiz</button></form><?php endif;?><?php require __DIR__.'/../includes/footer.php'; ?>
